### ISSUE TITLE
What is license of this project?

### ISSUE THREAD

**Issue by maxtortime** [vmi356/filemanager#13]
I cannot find information about license.

How I know license of this repository?

I want to use this code in [here](https://github.com/maxtortime/SetupBox) and I improved this filemanager.

Thanks

**Comment by summerisgone** [comment]
@maxtortime I've added license section to README file. Actually I didn't thought that it is necessary :)

**Comment by maxtortime** [comment]
Thanks. You don't need to care this issue because I wrote this issue before
sending email.

2016년 3월 11일 (금) 04:04, Ivan Gromov notifications@github.com님이 작성:

> @maxtortime https://github.com/maxtortime I've added license section to
> README file. Actually I didn't thought that it is necessary :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vmi356/filemanager/issues/13#issuecomment-195002800.
> 
> ## 

Taehwan Kim
FAST Lab. (http://fast.ajou.ac.kr)
Ajou University
